name: Lint and Standards
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm lint
